# numpy slicing 

I load a csv file into numpy. I want to slice out part of the resulting array to put into VTK.

Let's load in some data

In [18]:
from StringIO import StringIO
import numpy as np

In [14]:
fname='/Users/lyon/Development/g-2/projects/20150529/try/fieldLookup_000001_fieldOut.csv'
d = np.genfromtxt(fname, dtype='<i4,<f8,<f8,<f8,<f8,<f8,<f8,<f8', delimiter=',', autostrip=True, names=True)

In [11]:
d

array([(7.0, 6670.1, 8.28192, -5025.02, 72.5177, -0.0, -0.0, 0.0),
       (0.0, 6670.1, 8.28192, -5025.02, 72.5177, 0.0, 0.0, -0.0),
       (0.0, 6679.22, 7.71508, -4950.63, 72.5177, 0.000260298, -0.00661571, -0.000158726),
       ...,
       (3.0, 7156.83, -12.3192, -749.617, 86.8804, -0.0171781, 0.786486, -0.17565),
       (0.0, 7156.85, -12.3283, -749.602, 86.8804, -0.000507018, 1.45243, 1.70694e-05),
       (3.0, 7156.85, -12.3283, -749.602, 86.8804, -0.0171662, 0.790942, -0.176443)], 
      dtype=[('name', '<f8'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8'), ('t', '<f8'), ('Bx', '<f8'), ('By', '<f8'), ('Bz', '<f8')])

In [26]:
d.shape

(1278824,)

In [27]:
d[50]

(7, 6670.1, 8.28169, -5024.99, 72.5177, -0.0, -0.0, 0.0)

In [28]:
d["Bx"]

array([-0.        ,  0.        ,  0.0002603 , ..., -0.0171781 ,
       -0.00050702, -0.0171662 ])

Note what's going on here. I don't have a matrix like array. I have an array of rows. This is because the array is not homogeneous and the colums have names. Had I removed the names and made each column the same time, then I'd have a real `ndarray`. What I have here is a "structured" or "record" array. See http://docs.scipy.org/doc/numpy/user/basics.rec.html for more info.

Note that the `<` in the `dtype` indicates "little endien"

Here's how to access more than one column

In [29]:
d[['x', 'y','z']]

array([(6670.1, 8.28192, -5025.02), (6670.1, 8.28192, -5025.02),
       (6679.22, 7.71508, -4950.63), ..., (7156.83, -12.3192, -749.617),
       (7156.85, -12.3283, -749.602), (7156.85, -12.3283, -749.602)], 
      dtype=[('x', '<f8'), ('y', '<f8'), ('z', '<f8')])

See http://wiki.scipy.org/Cookbook/Recarray for converting to a regular array

In [32]:
d.dtype

dtype([('name', '<i4'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8'), ('t', '<f8'), ('Bx', '<f8'), ('By', '<f8'), ('Bz', '<f8')])

In [34]:
d.dtype.names

('name', 'x', 'y', 'z', 't', 'Bx', 'By', 'Bz')

We need to convert the structured array into a regular array

In [50]:
d[['x', 'y', 'z']].view( (np.float, 3) )

array([[ 6670.1    ,     8.28192, -5025.02   ],
       [ 6670.1    ,     8.28192, -5025.02   ],
       [ 6679.22   ,     7.71508, -4950.63   ],
       ..., 
       [ 7156.83   ,   -12.3192 ,  -749.617  ],
       [ 7156.85   ,   -12.3283 ,  -749.602  ],
       [ 7156.85   ,   -12.3283 ,  -749.602  ]])

In [61]:
d["name"].ravel()

array([7, 0, 0, ..., 3, 0, 3], dtype=int32)

In [56]:
np.int

int