# Muon Movie

We have an np array of track IDs

In [1]:
import numpy as np

In [24]:
trkIds = np.array([1,1,1,1,1,2,2,2,3,3])

Let's find the breaks (see http://stackoverflow.com/questions/19125661/find-index-where-elements-change-value-nump)

In [25]:
breaks = np.where( trkIds[:-1] != trkIds[1:] )[0] ; breaks

array([4, 7])

So the first track ends at element 4, the second track ends at element 7. It doesn't say where the third track ends, but it ends at `len(ids)-1`

In [26]:
breaks = np.append(breaks, [len(trkIds)-1]) ; breaks

array([4, 7, 9])

In [27]:
npoints = np.append( breaks[0]+1, np.diff(breaks)) ; npoints

array([5, 3, 2])

In [28]:
ncells = npoints-1 ; ncells

array([4, 2, 1])

In [29]:
np.sum(ncells)

7